# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mint/v3/events.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class EventTokenomicsSet(betterproto.Message):
    staked_token_amount: str = betterproto.string_field(1)
    circulating_supply: str = betterproto.string_field(2)
    emissions_amount: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class EventEcosystemTokenMintSet(betterproto.Message):
    block_height: int = betterproto.uint64_field(1)
    token_amount: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class EventRewardCurrentBlockEmission(betterproto.Message):
    block_height: int = betterproto.uint64_field(1)
    token_amount: str = betterproto.string_field(2)
