"""
Cross-language differential test: Python `canonicalize_dec` must match
`allora-chain/math.Dec.Marshal()` byte-for-byte.

Ground truth is generated by `tests/canon/gen_canon.go` against the live
chain code. To regenerate after a chain change:

    cd tests/canon && go run gen_canon.go > canon_ground_truth.json
"""

from __future__ import annotations

import json
from decimal import Decimal
from pathlib import Path

import pytest

from allora_sdk.rpc_client.dec_canonical import canonicalize_dec


_GROUND_TRUTH_PATH = Path(__file__).parent / "canon" / "canon_ground_truth.json"


def _load_ground_truth() -> list[tuple[str, str]]:
    with _GROUND_TRUTH_PATH.open() as f:
        data = json.load(f)
    return [(p["input"], p["output"]) for p in data]


GROUND_TRUTH = _load_ground_truth()


@pytest.mark.parametrize("input_str,expected", GROUND_TRUTH, ids=[p[0] for p in GROUND_TRUTH])
def test_matches_chain_canonical_form(input_str: str, expected: str) -> None:
    """Python output must equal the chain's `Dec.Marshal()` byte-for-byte."""
    actual = canonicalize_dec(input_str)
    assert actual == expected, f"input={input_str!r}: got {actual!r}, want {expected!r}"


@pytest.mark.parametrize("input_str,expected", GROUND_TRUTH, ids=[p[0] for p in GROUND_TRUTH])
def test_decimal_input_matches(input_str: str, expected: str) -> None:
    """Passing a `Decimal` directly produces the same output as passing the string."""
    actual = canonicalize_dec(Decimal(input_str))
    assert actual == expected


@pytest.mark.parametrize(
    "float_val,expected",
    [
        # Python's `str()` for these floats produces input apd accepts;
        # ground truth was generated for the str-form alongside.
        (1.2345e-7, "1.2345E-7"),
        (1.2345e-6, "0.0000012345"),
        (1.2345, "1.2345"),
        (0.0, "0.0"),
        (-0.0, "-0.0"),
        (100.0, "100.0"),
        (1e20, "1E+20"),
        (1e-5, "0.00001"),
        (0.1, "0.1"),
    ],
    ids=lambda v: repr(v),
)
def test_float_input(float_val: float, expected: str) -> None:
    """Passing a Python float produces the same canonical form via str(float)."""
    assert canonicalize_dec(float_val) == expected


@pytest.mark.parametrize(
    "non_finite",
    [float("nan"), float("inf"), float("-inf"), Decimal("NaN"), Decimal("Infinity"), Decimal("-Infinity")],
    ids=["nan_float", "posinf_float", "neginf_float", "nan_dec", "posinf_dec", "neginf_dec"],
)
def test_non_finite_rejected(non_finite) -> None:
    """Non-finite values must raise rather than producing an unsignable string."""
    with pytest.raises(ValueError):
        canonicalize_dec(non_finite)


@pytest.mark.parametrize(
    "bad_string",
    ["", "abc", "1.2.3", "--1", "1e", "0x10"],
)
def test_unparseable_string_raises(bad_string: str) -> None:
    with pytest.raises(ValueError):
        canonicalize_dec(bad_string)


def test_int_input() -> None:
    """Plain ints round-trip cleanly."""
    assert canonicalize_dec(0) == "0"
    assert canonicalize_dec(1) == "1"
    assert canonicalize_dec(-42) == "-42"
    assert canonicalize_dec(1234567890) == "1234567890"


def test_unsupported_type_raises() -> None:
    with pytest.raises(TypeError):
        canonicalize_dec([1, 2, 3])  # type: ignore[arg-type]


# === Sanity check: the float→str conversion we rely on actually produces
# what we expect on this Python build. If a future Python version changes
# the float repr rules, this guards against silent canonicalization drift.

@pytest.mark.parametrize(
    "float_val,expected_str",
    [
        (1.2345e-7, "1.2345e-07"),
        (1.2345, "1.2345"),
        (0.0, "0.0"),
        (-0.0, "-0.0"),
    ],
)
def test_str_float_baseline(float_val: float, expected_str: str) -> None:
    assert str(float_val) == expected_str
