wallet:
  mnemonic_file: /run/secrets/allora_mnemonic

network:
  chain_id: allora-testnet-1
  url: grpc+https://allora-grpc.testnet.allora.network:443
  websocket_url: wss://allora-rpc.testnet.allora.network/websocket
  fee_denom: uallo
  fee_minimum_gas_price: 10

workers:
  - role: inferer
    topic_id: 69
    inference_source:
      type: api
      url: http://model-api:8000/inference?block={nonce}
      method: GET
      response_field: value
