# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: mint/module/v1/module.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Module(betterproto.Message):
    """Module is the config object of the mint module."""

    fee_collector_name: str = betterproto.string_field(1)
