# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: emissions/module/v1/module.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Module(betterproto.Message):
    """
    Module is the app config object of the module.
     Learn more: https://docs.cosmos.network/main/building-modules/depinject
    """

    fee_collector_name: str = betterproto.string_field(1)
